### ISSUE TITLE
Documentation - no mention of default directory for content

### ISSUE THREAD

**Issue by JCombee** [roelofjan-elsinga/aloia-cms#24]
When I was looking through the documentation I couldn't find a mention of the default location of the content.

I had to find out in the error where exactly this is stored. I think the location's where `config('aloiacms.collection_path')` is mentioned it would be interesting to know where the collection folder defaults to.

**Comment by incredimike** [comment]
Examples of (1) what the file / directory structure looks like, and (2) what happens to the file system when a model is created, updates or deleted would be extremely helpful for wrapping my head around the concepts

**Comment by roelofjan-elsinga** [comment]
@JCombee and @incredimike I've written more about this here: https://aloiacms.com/file-structure

Can you let me know if this clarifies things or if it needs more/different information?

**Comment by incredimike** [comment]
Yeah this is great. Thank you. I think it will be especially helpful to people who are trying to import existing data.

**Comment by roelofjan-elsinga** [comment]
> Yeah this is great. Thank you. I think it will be especially helpful to people who are trying to import existing data. 

Agreed!
